# Generated by Django 6.0 on 2026-01-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='ai_generated_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
