# Generated by Django 6.0 on 2026-01-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_deal_ai_generated_reply_deal_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='subject',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='deal',
            name='thread_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
