# Generated by Django 4.2.7 on 2026-09-05 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deals', '0004_delete_email_emailmessage_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=40)),
                ('provider', models.CharField(blank=True, default='', max_length=40)),
                ('model', models.CharField(blank=True, default='', max_length=120)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=40)),
                ('success', models.BooleanField(default=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('error_type', models.CharField(blank=True, default='', max_length=80)),
                ('summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HumanAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('reason', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NegotiationTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField(default=1)),
                ('client_message', models.TextField(blank=True, default='')),
                ('ai_reply', models.TextField(blank=True, default='')),
                ('decision', models.CharField(blank=True, default='', max_length=40)),
                ('offer_amount', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='deal',
            name='budget_offered',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='deal',
            name='extracted_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='deal',
            name='human_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deal',
            name='human_required_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='deal',
            name='intent',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='deal',
            name='last_ai_decision',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='deal',
            name='last_ai_model',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='deal',
            name='last_ai_provider',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='deal',
            name='min_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='negotiation_round',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deal',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], db_index=True, default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='deal',
            name='rag_facts_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='deal',
            name='send_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deal',
            name='spam_decision',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='deal',
            name='target_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='attachment_metadata_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='body_html',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='body_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='gmail_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='headers_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='labels_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='reply_to',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='thread_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='urls_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('WAITING_FOR_CLIENT', 'Waiting for Client'), ('PENDING_CREATOR', 'Pending Creator Decision'), ('HUMAN_REQUIRED', 'Human Required'), ('REVIEW', 'Review'), ('NEED_INFORMATION', 'Need Information'), ('SPAM', 'Spam'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('AUTO_REJECTED', 'Auto Rejected')], db_index=True, default='NEW', max_length=30),
        ),
        migrations.AlterField(
            model_name='deal',
            name='thread_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='to_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['status', 'priority'], name='deals_deal_status_1d6686_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['-updated_at'], name='deals_deal_updated_bf2d2f_idx'),
        ),
        migrations.AddField(
            model_name='negotiationturn',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiation_turns', to='deals.deal'),
        ),
        migrations.AddField(
            model_name='humanaction',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human_actions', to='deals.deal'),
        ),
        migrations.AddField(
            model_name='humanaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiinteraction',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_interactions', to='deals.deal'),
        ),
        migrations.AddField(
            model_name='aiinteraction',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_interactions', to='deals.emailmessage'),
        ),
    ]
